import { NewsModels } from '../models/news-models';

export const fakeNews: () => NewsModels.List.ResponseParams = () => ({
  'status': 'ok',
  'totalResults': 38,
  'articles': [
    {
      'source': {
        'id': 'cnn',
        'name': 'CNN',
      },
      'author': 'Frank Pallotta, CNN Business',
      'title': 'Netflix is trying to beat competitors by adding video games - CNN',
      'description': 'Netflix is the king of streaming with more than 200 million subscribers. But now it appears the platform has set its sights on dominating a new form of entertainment: video games.',
      'url': 'https://www.cnn.com/2021/07/15/media/netflix-video-games/index.html',
      'urlToImage': 'https://cdn.cnn.com/cnnnext/dam/assets/201020150544-03-netflix---stock-super-tease.jpg',
      'publishedAt': '2021-07-15T20:43:00Z',
      'content': null,
    },
    {
      'source': {
        'id': 'associated-press',
        'name': 'Associated Press',
      },
      'author': 'Josh Boak',
      'title': 'Child tax credit starts hitting US families\' bank accounts - Associated Press',
      'description': 'WASHINGTON (AP) — The child tax credit  had always been an empty gesture to millions of parents like Tamika Daniel.',
      'url': 'https://apnews.com/article/child-tax-credit-bank-accounts-0715-24023ed3ffba98e4a65dd6006518da7a',
      'urlToImage': 'https://storage.googleapis.com/afs-prod/media/eafce6108c894c04b6cc2c33edd75c4f/3000.jpeg',
      'publishedAt': '2021-07-15T20:20:46Z',
      'content': 'WASHINGTON (AP) The child tax credit had always been an empty gesture to millions of parents like Tamika Daniel.\r\nThat changed Thursday when the first payment of $1,000 hit Daniels bank account and d… [+6580 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'Gizmodo.com',
      },
      'author': 'Tom McKay',
      'title': '$28 Million Ticket-Holder for Jeff Bezos’s Flight to Space Suddenly Has Something Better to Do - Gizmodo',
      'description': 'The mystery bidder who won a seat on the maiden crewed flight of the New Shepard rocket now has... "scheduling conflicts."',
      'url': 'https://gizmodo.com/28-million-ticket-holder-for-jeff-bezos-s-flight-to-sp-1847301151',
      'urlToImage': 'https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/bf30614d716f5381ff3ce6b7827160e4.jpg',
      'publishedAt': '2021-07-15T20:00:00Z',
      'content': 'The person who paid $28 million for a seat to the edge of space with billionaire Amazon magnate Jeff Bezos on one of his Blue Origin rockets has decided they have better things to do.\r\nOn July 20, Be… [+2852 chars]',
    },
    {
      'source': {
        'id': 'google-news',
        'name': 'Google News',
      },
      'author': null,
      'title': 'Ric Bucher gives his biggest takeaways from Bucks\' Game 4 win vs. Suns in Finals | NBA | THE HERD - The Herd with Colin Cowherd',
      'description': null,
      'url': 'https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9UENyR0stSFh0R1nSAQA?oc=5',
      'urlToImage': null,
      'publishedAt': '2021-07-15T19:48:18Z',
      'content': null,
    },
    {
      'source': {
        'id': null,
        'name': 'CNBC',
      },
      'author': 'Greg Iacurci',
      'title': 'Democrats\' budget prohibits higher taxes for those making less than $400,000. Here\'s who might pay more - CNBC',
      'description': 'Senate Democrats issued a budget framework Wednesday that calls for higher taxes on the rich and more tax enforcement, similar to President Biden\'s tax plan.',
      'url': 'https://www.cnbc.com/2021/07/15/democrats-budget-bars-tax-hikes-for-most-but-heres-who-may-pay-more.html',
      'urlToImage': 'https://image.cnbcfm.com/api/v1/image/106911613-1626374337672-gettyimages-1233977722-775682189.jpeg?v=1626376794',
      'publishedAt': '2021-07-15T19:41:40Z',
      'content': 'Senate Majority Leader Chuck Schumer, D-N.Y., and President Joe Biden arrive at the U.S. Capitol for a Senate Democratic luncheon on July 14, 2021.\r\nSenate Democrats aim to fund a $3.5 trillion budge… [+5153 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'Hollywood Reporter',
      },
      'author': 'Kim Masters',
      'title': 'Netflix Fires Marketing Execs for Criticizing Bosses Over Slack - Hollywood Reporter',
      'description': 'Netflix has dismissed three senior film marketing executives — about half its staff at that level — after they were discovered grousing on Slack about management, sources tell The Hollywood Reporter. According to sources, their immediate boss, vp original fil…',
      'url': 'https://www.hollywoodreporter.com/business/business-news/netflix-fires-execs-over-slack-comments-1234982361/',
      'urlToImage': 'https://www.hollywoodreporter.com/wp-content/uploads/2021/07/GettyImages-1232290222-H-2021.jpg?w=1024',
      'publishedAt': '2021-07-15T19:39:13Z',
      'content': 'Netflix has dismissed three senior film marketing executives — about half its staff at that level — after they were discovered grousing on Slack about management, sources tell The Hollywood Reporter.… [+4235 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'NPR',
      },
      'author': 'Sharon Pruitt-Young',
      'title': 'Jury Finds Capital Gazette Gunman Responsible And Rejects His Mental Illness Plea - NPR',
      'description': 'Jarrod Ramos, who carried out the attack on Capital Gazette, admitted to five murders. On Thursday a jury found he understood what he was doing.',
      'url': 'https://www.npr.org/2021/07/15/1015483036/jury-rejects-capital-gazette-gunmans-mental-illness-plea',
      'urlToImage': 'https://media.npr.org/assets/img/2021/07/15/ap21176773458615_wide-6cd215146b21981dec972b6ccc91c995247e4bc1.jpg?s=1400',
      'publishedAt': '2021-07-15T19:27:19Z',
      'content': 'Five employees of the Capital Gazette newspaper are honored across the street from where the the newsroom where they were killed in Annapolis, Md.\r\nJose Luis Magana/AP\r\nThe gunman who admitted to a s… [+4815 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'CBS Sports',
      },
      'author': '',
      'title': 'Team USA basketball: Bradley Beal to miss Tokyo Olympics; U.S. seeking replacement - CBS Sports',
      'description': 'Beal is a first-time Olympian and had started every exhibition game for Team USA to this point',
      'url': 'https://www.cbssports.com/nba/news/team-usa-basketball-bradley-beal-to-miss-tokyo-olympics-u-s-seeking-replacement/',
      'urlToImage': 'https://sportshub.cbsistatic.com/i/r/2021/07/15/caeb4b8a-4d5d-42f8-98ce-7028096b540b/thumbnail/1200x675/a1221dcc66dd4bfeb930b490b7e87344/untitled-design-2021-07-14t202816-782.png',
      'publishedAt': '2021-07-15T19:16:00Z',
      'content': 'The U.S. men\'s basketball team announced Thursday afternoon that Washington Wizards guard Bradley Beal will miss the Tokyo Olympics this summer as he\'s entered the health and safety protocols at Team… [+2488 chars]',
    },
    {
      'source': {
        'id': 'cbs-news',
        'name': 'CBS News',
      },
      'author': 'Sophie Lewis',
      'title': 'NASA: Moon "wobble" in orbit may lead to record flooding on Earth - CBS News',
      'description': 'A wobble in the moon\'s orbit will raise high tides even higher, exacerbating the devastating effects of sea-level rise.',
      'url': 'https://www.cbsnews.com/news/nasa-moon-wobble-orbit-record-flooding-earth-sea-level-rise-climate-change/',
      'urlToImage': 'https://cbsnews3.cbsistatic.com/hub/i/r/2021/07/13/d1eba35a-bca7-4da4-a4ae-5b428ead6929/thumbnail/1200x630/d68bb15705703c50def51513f77f2735/gettyimages-490700730.jpg',
      'publishedAt': '2021-07-15T19:13:10Z',
      'content': 'Every coast in the U.S. is facing rapidly increasing high tide floods. NASA says this is due to a "wobble" in the moon\'s orbit working in tandem with climate change-fueled rising sea levels.\r\nThe new… [+3397 chars]',
    },
    {
      'source': {
        'id': 'the-verge',
        'name': 'The Verge',
      },
      'author': 'Brandon Widder',
      'title': 'Where to preorder the Nintendo Switch OLED model - The Verge',
      'description': 'The Nintendo Switch OLED model, the latest iteration of Nintendo’s blockbuster handheld, will go on sale on October 8th for $350. Right now, you can preorder the console at Walmart.',
      'url': 'https://www.theverge.com/22565905/nintendo-switch-oled-model-preorder-price-availability-where-to-buy',
      'urlToImage': 'https://cdn.vox-cdn.com/thumbor/xN-jLvVpbNggPEc4UjQfuPAZNTI=/0x38:1920x1043/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/22701633/oled_model_photo_01.png',
      'publishedAt': '2021-07-15T19:08:29Z',
      'content': 'Coming October 8th for $350\r\nIf you buy something from a Verge link, Vox Media may earn a commission. See our ethics statement.\r\nImage: Nintendo\r\nUpdate July 15th, 4:55PM ET: The Nintendo Switch OLED… [+2611 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'Panthers.com',
      },
      'author': null,
      'title': 'Panthers agree to terms with Taylor Moton - Panthers.com - Panthers.com',
      'description': 'The franchise-tagged right tackle gets his new deal the day of the deadline.',
      'url': 'https://www.panthers.com/news/panthers-agree-to-terms-with-taylor-moton',
      'urlToImage': 'https://static.clubs.nfl.com/image/private/t_editorial_landscape_12_desktop/panthers/w5ij6sgouuyznwoekyz8',
      'publishedAt': '2021-07-15T19:04:35Z',
      'content': 'CHARLOTTE The Panthers knew they didn\'t have to worry about Taylor Moton\'s contract for this year.\r\nNow, they don\'t have to worry about it for the next several.\r\nMoton, the team\'s franchise player, h… [+1341 chars]',
    },
    {
      'source': {
        'id': 'fox-news',
        'name': 'Fox News',
      },
      'author': 'Brandon Gillespie',
      'title': 'Meghan McCain flames Britney Spears\' family over conservatorship \'abuse\': \'Go to hell everyone!\' - Fox News',
      'description': '"The View" co-host Meghan McCain flamed the family of Britney Spears on Thursday, slamming them over treatment the pop star has allegedly endured during the 13-year conservatorship from her father, Jamie Spears.',
      'url': 'https://www.foxnews.com/media/meghan-mccain-flames-britney-spears-family-conservatorship-abuse',
      'urlToImage': 'https://static.foxnews.com/foxnews.com/content/uploads/2021/07/Mccain-Spears-GETTY-REUTERS.jpg',
      'publishedAt': '2021-07-15T18:34:49Z',
      'content': '"The View" co-host Meghan McCain flamed the family of Britney Spears on Thursday, slamming them over treatment the pop star has allegedly endured during the 13-year conservatorship from her father, J… [+2232 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'The Guardian',
      },
      'author': 'Luke Harding, Dan Sabbagh',
      'title': 'The person to ‘weaken’ America: what the Kremlin papers said about Trump - The Guardian',
      'description': 'Documents appear to show how Russian intelligence worked to install their preferred candidate as president',
      'url': 'https://amp.theguardian.com/world/2021/jul/15/the-person-to-weaken-america-what-the-kremlin-papers-said-about-trump',
      'urlToImage': null,
      'publishedAt': '2021-07-15T18:25:00Z',
      'content': 'RussiaThu 15 Jul 2021 18.05 BST\r\nIn January 2016, America was coming to terms with what had previously seemed incredible. Barring an unforeseen event, Donald J Trump was on course to become the Repub… [+10245 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'Nature.com',
      },
      'author': null,
      'title': 'Highly accurate protein structure prediction with AlphaFold - Nature.com',
      'description': 'Proteins are essential to life, and understanding their structure can facilitate a mechanistic understanding of their function. Through an enormous experimental effort1–4, the structures of around 100,000 unique proteins have been determined5, but this repres…',
      'url': 'https://www.nature.com/articles/s41586-021-03819-2',
      'urlToImage': null,
      'publishedAt': '2021-07-15T18:24:58Z',
      'content': 'DeepMind, London, UK\r\nJohn Jumper, Richard Evans, Alexander Pritzel, Tim Green, Michael Figurnov, Olaf Ronneberger, Kathryn Tunyasuvunakool, Russ Bates, Augustin ídek, Anna Potapenko, Alex Bridgland,… [+374 chars]',
    },
    {
      'source': {
        'id': 'fox-news',
        'name': 'Fox News',
      },
      'author': 'Charles Creitz',
      'title': 'Lara Logan: South Africa\'s unrest \'eerily similar\' to racial tensions in US - Fox News',
      'description': 'As mass chaos, looting, resource shortages and mounting racial tensions grip South Africa, but go largely uncovered in United States media, Fox Nation host Lara Logan – a native of South Africa – explained the dangerous conditions terrorizing the people of th…',
      'url': 'https://www.foxnews.com/media/lara-logan-south-africa-unrest-ingraham',
      'urlToImage': 'https://static.foxnews.com/foxnews.com/content/uploads/2020/08/logan.jpg',
      'publishedAt': '2021-07-15T18:19:42Z',
      'content': 'As mass chaos, looting, resource shortages and mounting racial tensions grip South Africa, but go largely uncovered in United States media, Fox Nation host Lara Logan a native of South Africa explain… [+3592 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'KOMO News',
      },
      'author': 'Suzanne Phan, KOMO News Reporter',
      'title': 'Drug overdose deaths spike in 2020 during pandemic - KOMO News',
      'description': 'According to the CDC, drug overdose deaths in 2020 during the COVID-19 pandemic reached an all-time high. The record 93,000 deaths last year is 30% higher than in 2019. Olga Davido-Beirer lost her son, Lucas to a drug overdose in 2019. He was a football playe…',
      'url': 'https://komonews.com/news/local/drug-overdose-deaths-spike-in-2020-during-pandemic',
      'urlToImage': 'https://static-31.sinclairstoryline.com/resources/media/4d09a17e-bbf2-42a6-8228-528799a0921b-large16x9_Fentanyl__DEA.png?1626373068768',
      'publishedAt': '2021-07-15T18:18:15Z',
      'content': null,
    },
    {
      'source': {
        'id': null,
        'name': 'CNBC',
      },
      'author': 'Thomas Franck',
      'title': 'Fed Chair Powell grilled by grouchy senators over inflation and climate change, even as economy rebounds - CNBC',
      'description': 'An economic rebound, rising wages and declining unemployment weren\'t enough to spare Fed Chairman Jerome Powell from gripes in the Senate.',
      'url': 'https://www.cnbc.com/2021/07/15/fed-chair-powell-faces-grumpy-senators.html',
      'urlToImage': 'https://image.cnbcfm.com/api/v1/image/106911403-1626357900954-powell.jpg?v=1626357925',
      'publishedAt': '2021-07-15T17:52:58Z',
      'content': 'An economic rebound, rising wages and declining unemployment claims weren\'t enough to spare Federal Reserve Chairman Jerome Powell on Thursday from gripes in the Senate.\r\nDuring testimony before the … [+5272 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'New York Times',
      },
      'author': 'Anna Perling',
      'title': 'How to Make Excellent Ice Cream at Home - The New York Times',
      'description': 'We’ve reviewed ice cream makers since 2014. Based on our years of research and testing, here are our tips for making better ice cream at home.',
      'url': 'https://www.nytimes.com/wirecutter/guides/tips-making-ice-cream-at-home/',
      'urlToImage': 'https://cdn.thewirecutter.com/wp-content/media/2021/07/icecreammaker-2048px-0315-2x3-1.jpg?auto=webp&quality=60&crop=1.91:1&width=1200',
      'publishedAt': '2021-07-15T17:50:16Z',
      'content': 'Working on the 2021 update to our ice cream maker guide was a formative ice cream experience of its own. After churning more than 40 pints while testing, Im now enamored with making the stuff myself.… [+1457 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'XDA Developers',
      },
      'author': 'Rich Woods',
      'title': 'New Windows 11 preview comes with a new widget and acrylic context menus - XDA Developers',
      'description': 'Microsoft released a new Windows 11 Insider Preview build today, and along with a lot of fixes, the biggest change is acrylic context menus.',
      'url': 'https://www.xda-developers.com/windows-11-preview-new-widget-acrylic-context-menus/',
      'urlToImage': 'https://www.xda-developers.com/files/2021/06/Windows-11-option-7.jpg',
      'publishedAt': '2021-07-15T17:25:00Z',
      'content': 'Today, Microsoft is releasingWindows 11 Insider Preview build 22000.71 to the Dev channel. It seems to be the case that the company isn’t going to be seeding a lot of new features through the Windows… [+12702 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'Daily Mail',
      },
      'author': 'Stacy Liberatore',
      'title': 'NASA\'s $1.1 billion Juno spacecraft snaps \'starship captain\' view images of Jupiter and Ganymede - Daily Mail',
      'description': 'NASA\'s Juno captured stunning images of Jupiter and its moon, Ganymede. The spectacular time-lapse takes viewers within 645 miles of Ganymede and 2,100 miles above Jupiter.',
      'url': 'https://www.dailymail.co.uk/sciencetech/article-9792361/NASAs-1-1-billion-Juno-spacecraft-snaps-starship-captain-view-images-Jupiter-Ganymede.html',
      'urlToImage': 'https://i.dailymail.co.uk/1s/2021/07/15/18/45491841-0-image-a-46_1626368610053.jpg',
      'publishedAt': '2021-07-15T17:22:09Z',
      'content': 'NASA has released a \'starship captain\' point of view of Jupiter and its moon, Ganymede, in a series of images captured by the Juno probe before and after making its 34th flyby of the gas giant.\r\nThe … [+6952 chars]',
    },
    {
      'source': {
        'id': 'fox-news',
        'name': 'Fox News',
      },
      'author': 'Julia Musto',
      'title': 'Arizona hit hard with flash flooding in wildfire burn scar - Fox News',
      'description': 'After weeks of scorching heat and devastating drought, Arizona cities have been inundated with flash flooding.',
      'url': 'https://www.foxnews.com/us/arizona-hit-hard-with-flash-flooding-in-wildfire-burn-scar',
      'urlToImage': 'https://static.foxnews.com/foxnews.com/content/uploads/2021/07/Flagstaff1.jpeg',
      'publishedAt': '2021-07-15T17:14:40Z',
      'content': 'After weeks of scorching heat and devastating drought, Arizona cities have been inundated with flash flooding. \r\nResidents of the Copper State which has been ravaged by wildfires, some sparked by lig… [+2779 chars]',
    },
    {
      'source': {
        'id': 'ign',
        'name': 'IGN',
      },
      'author': 'Bo Moore',
      'title': 'Steam Deck: The First Hands-On With Valve’s Handheld Gaming PC - IGN - IGN',
      'description': 'Our impressions of the Steam Deck, Valve\'s new handheld PC gaming device.',
      'url': 'https://www.ign.com/articles/steam-deck-hands-on-impressions-details-valve-handheld-gaming-pc',
      'urlToImage': 'https://assets-prd.ignimgs.com/2021/07/14/steamdeck-handson-blogroll-1626306023078.jpg?width=1280',
      'publishedAt': '2021-07-15T17:04:54Z',
      'content': 'Today Valve announced the Steam Deck\r\n, a brand-new handheld PC gaming device. Last week, IGN had the exclusive opportunity to visit Valve for the very first hands-on with the Steam Deck, as well as … [+12661 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'Investor\'s Business Daily',
      },
      'author': 'Investor\'s Business Daily',
      'title': 'Dow Jones Reverses, Tech Stocks Slide As Powell Defends Fed Policy; Tesla Skids, AMC Stock Surges - Investor\'s Business Daily',
      'description': 'The Dow Jones Industrial Average reversed higher Thursday, as Fed chief Powell spoke to the Senate. Tesla rallied, while AMC stock reversed.',
      'url': 'https://www.investors.com/market-trend/stock-market-today/dow-jones-falls-as-powell-speaks-to-senate-tesla-rallies-amc-stock-reverses/',
      'urlToImage': 'https://www.investors.com/wp-content/uploads/2018/10/stock-Jerome-Powell-02-fed.jpg',
      'publishedAt': '2021-07-15T17:00:00Z',
      'content': 'The Dow Jones Industrial Average briefly dropped 150 points before reversing higher Thursday, as Fed chief Jerome Powell testified in front of the U.S. Senate. Tesla looked to add to two days of loss… [+6386 chars]',
    },
    {
      'source': {
        'id': 'buzzfeed',
        'name': 'Buzzfeed',
      },
      'author': '[{"@type":"Person","name":"Emily Mae Czachor","url":"https://www.buzzfeed.com/emilymaeczachor","jobTitle":"BuzzFeed Staff"}]',
      'title': 'These Pics Of Tilda Swinton And Her Daughter At Cannes Will Absolutely Make Your Day - BuzzFeed',
      'description': 'Family bonding but make it fashion!',
      'url': 'https://www.buzzfeed.com/emilymaeczachor/tilda-swinton-daughter-cannes-red-carpet-pics',
      'urlToImage': 'https://img.buzzfeed.com/buzzfeed-static/static/2021-07/15/14/enhanced/2ae2219c27cd/original-460-1626360849-2.jpg?crop=1019:533;0,146%26downsize=1250:*',
      'publishedAt': '2021-07-15T16:47:33Z',
      'content': 'Lionel Hahn / Getty Images\r\nBoth Tilda and Honor star in Joanna Hogg\'s The Souvenir Part II, which premiered at Cannes last week.',
    },
    {
      'source': {
        'id': 'the-washington-post',
        'name': 'The Washington Post',
      },
      'author': 'Philip Rucker, Carol D. Leonnig',
      'title': '\'I Alone Can Fix It\' book excerpt: The inside story of Trump\'s defiance and inaction on Jan. 6 - The Washington Post',
      'description': '',
      'url': 'https://www.washingtonpost.com/politics/2021/07/15/jan-6-i-alone-can-fix-it-book-excerpt/',
      'urlToImage': 'https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/AORVZ2GOEEI6XAAUF44SNSRE3E.jpg&w=1440',
      'publishedAt': '2021-07-15T16:01:05Z',
      'content': 'At the White House, Trump set the tone for the day with an 8:17 a.m. tweet: States want to correct their votes, which they now know were based on irregularities and fraud, plus corrupt process never … [+38248 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'ESPN',
      },
      'author': 'Bob Harig',
      'title': 'Jordan Spieth shoots first-round 65 at The Open - ESPN',
      'description': 'Jordan Spieth shot an opening 5-under 65 at Royal St. George\'s -- a course he\'d never played -- to put himself in good position after the first round of The Open.',
      'url': 'https://www.espn.com/golf/story/_/id/31822820/jordan-spieth-shoots-first-round-65-open',
      'urlToImage': 'https://a3.espncdn.com/combiner/i?img=%2Fphoto%2F2021%2F0715%2Fr880778_1296x729_16%2D9.jpg',
      'publishedAt': '2021-07-15T16:01:01Z',
      'content': 'SANDWICH, England -- Jordan Spieth has been near the top of leaderboards since February, so it makes sense he\'s in that position after his opening round at The Open.\r\nBut Spieth wasn\'t so sure that w… [+3935 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'Los Angeles Times',
      },
      'author': 'Rong-Gong Lin II, Luke Money',
      'title': 'Reconsider travel to Nevada, Florida amid COVID-19 surge - Los Angeles Times',
      'description': 'L.A. County health officer Dr. Muntu Davis suggests that residents reconsider travel to states with the highest rates of coronavirus transmission.',
      'url': 'https://www.latimes.com/california/story/2021-07-15/reconsider-travel-to-nevada-florida-amid-covid-19-surge',
      'urlToImage': 'https://ca-times.brightspotcdn.com/dims4/default/56a0672/2147483647/strip/true/crop/5043x2648+0+388/resize/1200x630!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F9a%2F9b%2F46eb45d545d68f3d53873bb10ea0%2Fla-photos-1staff-768501-na-tourism-returns-to-vegas2.jpg',
      'publishedAt': '2021-07-15T15:53:57Z',
      'content': 'The Los Angeles County health officer has suggested that residents reconsider travel to states with the nations worst rates of coronavirus transmission, including Nevada and Florida.\r\nI do want to re… [+3532 chars]',
    },
    {
      'source': {
        'id': 'the-washington-post',
        'name': 'The Washington Post',
      },
      'author': 'Sammy Westfall',
      'title': 'Dutch crime reporter Peter R. de Vries dies after being shot in the head - The Washington Post',
      'description': 'Despite regular death threats, the Dutch journalist did not live in fear.',
      'url': 'https://www.washingtonpost.com/world/2021/07/15/journalist-devries-dead/',
      'urlToImage': 'https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/5MK3MXXFNQI6XCGFJ7LDQLCHZM.jpg&w=1440',
      'publishedAt': '2021-07-15T15:50:24Z',
      'content': 'Peter has lived by his conviction: On bended knee is no way to be free. We are unbelievably proud of him and at the same time inconsolable, family members wrote in a statement, reported RTL News.\r\nHe… [+1427 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'KCRA Sacramento',
      },
      'author': 'Hope Miller',
      'title': 'Napa doctor faked COVID-19 vaccines, vaccine cards, DOJ says - KCRA Sacramento',
      'description': 'A Napa doctor has been arrested on suspicion of providing fake COVID-19 vaccination cards and so-called immunization pills, federal prosecutors say.',
      'url': 'https://www.kcra.com/article/napa-doctor-faked-covid-19-vaccines-vaccine-cards-doj-says/37035277',
      'urlToImage': 'https://kubrick.htvapps.com/htv-prod-media.s3.amazonaws.com/images/vaccine-card-1623699380.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*',
      'publishedAt': '2021-07-15T15:35:00Z',
      'content': 'NAPA, Calif. —A Napa doctor has been arrested on suspicion of providing fake COVID-19 vaccination cards and so-called immunization pills, federal prosecutors said Wednesday. \r\nThe case is the first f… [+2440 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'Variety',
      },
      'author': 'Caroline Framke',
      'title': 'With ‘Ted Lasso,’ Hannah Waddingham and Juno Temple’s On- and Off-Screen Friendship Flips the Sports Comedy Script - Variety',
      'description': 'When Hannah Waddingham and Juno Temple first met, in a ladies’ loo mere minutes before the inaugural table read for “Ted Lasso,” they barely exchanged words before knowing they wouldn’t have to fake the friendship that blooms between their characters. “It was…',
      'url': 'https://variety.com/2021/tv/features/ted-lasso-season-2-hannah-waddingham-juno-temple-1235019877/',
      'urlToImage': 'https://variety.com/wp-content/uploads/2021/07/Hannah-Waddingham-Juno-Temple-Variety-Cover-Story-16x9-1.jpg?w=1024',
      'publishedAt': '2021-07-15T15:01:05Z',
      'content': 'When Hannah Waddingham and Juno Temple first met, in a ladies’ loo mere minutes before the inaugural table read for “Ted Lasso,” they barely exchanged words before knowing they wouldn’t have to fake … [+19480 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'Gizmodo.com',
      },
      'author': 'George Dvorsky',
      'title': 'NASA Identifies ‘Possible Cause’ of Hubble Glitch - Gizmodo',
      'description': 'Operations are now underway to restore a failing computer on the storied space telescope.',
      'url': 'https://gizmodo.com/nasa-identifies-possible-cause-of-hubble-glitch-1847298221',
      'urlToImage': 'https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/793036d443e1f3b6e7617ed8f1fc7378.jpg',
      'publishedAt': '2021-07-15T14:50:00Z',
      'content': 'The Hubble recovery team thinks its finally tracked down a problem thats kept the space telescope out of commission for over a month.\r\nThe problem started on June 13, when an onboard computer suddenl… [+2391 chars]',
    },
    {
      'source': {
        'id': 'axios',
        'name': 'Axios',
      },
      'author': 'Barak Ravid',
      'title': 'Lebanese president defies U.S. and French pressure, rejects new government - Axios',
      'description': '"May God help Lebanon," Hariri said as he resigned.',
      'url': 'https://www.axios.com/lebanon-crisis-aoun-rejects-hariri-resigns-edc957d0-6fd1-4330-b48a-b051c7ff4a4e.html',
      'urlToImage': 'https://images.axios.com/dUEvKJiD7IKGOEDifrKHH7gVagQ=/0x246:2362x1575/1366x768/2021/07/15/1626358752905.jpg',
      'publishedAt': '2021-07-15T14:23:42Z',
      'content': 'Lebanese President Michel Aoun rejected Prime Minister-designate Saad Hariri\'s proposal for a new government, prompting Hariri\'s resignation and deepening the country\'s political crisis.\r\nWhy it matt… [+1602 chars]',
    },
    {
      'source': {
        'id': 'fox-news',
        'name': 'Fox News',
      },
      'author': 'Fox News Staff',
      'title': 'Concha: Democrats\' stunt with Texas election bill will \'blow up in their faces\' in 2022 - Fox News',
      'description': 'Fox News contributor Joe Concha told “Fox & Friends” on Thursday called out the Texas Democrats’ remaining in Washington D.C. to fight GOP voting reform, arguing their stunt will “blow up in their faces” in the upcoming midterm elections.',
      'url': 'https://www.foxnews.com/media/concha-texas-democrats-stunt-blow-up-midterms',
      'urlToImage': 'https://static.foxnews.com/foxnews.com/content/uploads/2021/07/Concha-The-Texas-Democrats-stunt-will-backfire-in-the-upcoming-midterms.jpeg',
      'publishedAt': '2021-07-15T14:20:22Z',
      'content': 'Fox News contributor Joe Concha called out the Texas Democrats remaining in Washington D.C. to fight GOP voting reform, telling "Fox &amp; Friends" on Thursday that the decision will "blow up in thei… [+1118 chars]',
    },
    {
      'source': {
        'id': 'the-washington-post',
        'name': 'The Washington Post',
      },
      'author': 'Dan Diamond, Hannah Knowles, Tyler Pager',
      'title': 'Vaccine hesitancy morphs into hostility, as opposition to shots hardens - The Washington Post',
      'description': 'The notion of coronavirus vaccines as unnecessary or harmful — or a government plot — is increasingly embraced by Trump supporters, complicating Biden’s push to boost the public’s immunity before autumn.',
      'url': 'https://www.washingtonpost.com/politics/covid-vaccines-biden-trump/2021/07/15/adaf6c7e-e4bd-11eb-a41e-c8442c213fa8_story.html',
      'urlToImage': 'https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/LDBJSQXFSAI6XJA6ZBCCYIJ7VA.jpg&w=1440',
      'publishedAt': '2021-07-15T14:01:54Z',
      'content': 'Clearly they were hoping the government was hoping that they could sort of sucker 90 percent of the population into getting vaccinated, activist Alex Berenson told the crowd Saturday, seeming to infl… [+11954 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'CNBC',
      },
      'author': 'Diana Olick',
      'title': 'The hot Miami condo market is a lot more complicated after tragic Surfside collapse - CNBC',
      'description': 'The deadly collapse of a residential tower spooked South Florida homebuyers and real estate investors into reassessing the risk of buying Miami-area condos.',
      'url': 'https://www.cnbc.com/2021/07/15/miami-condo-market-more-complicated-after-tragic-surfside-collapse.html',
      'urlToImage': 'https://image.cnbcfm.com/api/v1/image/106911357-1626353107467-gettyimages-1305077077-1006_03_fl210215d04.jpeg?v=1626353199',
      'publishedAt': '2021-07-15T13:42:06Z',
      'content': 'MIAMI The tragic collapse of a residential tower spooked South Florida homebuyers and real estate investors alike into reassessing the risk of buying in the Miami-area condo market.\r\nThe market had b… [+6436 chars]',
    },
    {
      'source': {
        'id': 'business-insider',
        'name': 'Business Insider',
      },
      'author': 'Dr. Catherine Schuster-Bruce',
      'title': 'GOP leaders back COVID-19 vaccines as red states struggle with shots - Business Insider',
      'description': 'Three senior Republicans have spoken up about the need to get COVID-19 shots. One said the politicization of vaccination was "an outrage."',
      'url': 'https://www.businessinsider.com/republicans-gop-covid-vaccines-red-states-mitt-romney-2021-7',
      'urlToImage': 'https://i.insider.com/60f02a3cbb790e0018207b1d?width=1200&format=jpeg',
      'publishedAt': '2021-07-15T13:31:18Z',
      'content': 'Three Republican leaders have spoken out in favor of COVID-19 shots as red-leaning states struggle to get people vaccinated while the highly infectious Delta variant rips across the US.\r\nSen. Mitt Ro… [+2023 chars]',
    },
    {
      'source': {
        'id': 'nbc-news',
        'name': 'NBC News',
      },
      'author': 'Rebecca Shabad',
      'title': 'Biden hosts German Chancellor Angela Merkel at White House - NBC News',
      'description': 'President Joe Biden will host German Chancellor Angela Merkel at the White House Thursday for possibly her last trip to Washington before she retires from office later this year.',
      'url': 'https://www.nbcnews.com/politics/white-house/biden-hosts-german-chancellor-angela-merkel-white-house-n1274019',
      'urlToImage': 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/newscms/2021_28/3491367/210715-kamala-harris-angela-merkel-al-1127.jpg',
      'publishedAt': '2021-07-15T11:39:00Z',
      'content': 'WASHINGTON President Joe Biden hosted German Chancellor Angela Merkel at the White House on Thursday for what is likely her last trip to Washington before she retires from office later this year.\r\n"I… [+1517 chars]',
    },
    {
      'source': {
        'id': null,
        'name': 'The Guardian',
      },
      'author': 'Emma Graham-Harrison',
      'title': 'Afghanistan\'s neighbours step up efforts to prevent civil war - The Guardian',
      'description': 'Rapid Taliban advances lead to meeting in Uzbekistan of over a dozen leaders and foreign ministers',
      'url': 'https://amp.theguardian.com/world/2021/jul/15/us-aims-to-woo-central-asian-leaders-for-secure-base-near-afghanistan',
      'urlToImage': 'https://i.guim.co.uk/img/media/d44522baa6b5a1ba4e49005783847b966b4a33f5/0_0_4139_2484/master/4139.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=0b39d7aed0543b439e3189f12bc8c216',
      'publishedAt': '2021-07-15T09:05:00Z',
      'content': 'Afghanistans neighbours are stepping up efforts to prevent the country sliding into a full-blown civil war after a rapid Taliban advance that caught the government in Kabul, its allies and much of th… [+5364 chars]',
    },
  ],
});
